### ISSUE TITLE
생방 다운은 되는데 예약 다운은 에러가 뜹니다..ㅠㅠ

### ISSUE THREAD

**Issue by Honinbo-Shusaku** [dltkddnr04/AfreecaTV-Auto-Recorder#1]
일부 비제이들은 정상적으로 받아지는 한편
몇몇 비제이들 아이디로는 아래와 같은 에러가 나옵니다..

[2023-10-23T19-12-51] Program started
Traceback (most recent call last):
  File "C:\AfreecaTV-Auto-Recorder-main\main.py", line 165, in <module>
    user_id = get_id_from_login(user_login)
  File "C:\AfreecaTV-Auto-Recorder-main\main.py", line 29, in get_id_from_login
    return result['CHANNEL']['BNO']
KeyError: 'BNO'

현재 생방중인 아이디는 정상적으로 작동하고
오프라인 상태일때 예약을 걸어두려고 하면 이런 에러가 뜨는 것 같습니다..
제가 혹시 뭐 잘못하고 있는 것이 있는건가요?

**Comment by dltkddnr04** [comment]
BNO를 가지고 닉네임이 바뀌어도 계속 다운로드가 되게 하는 기능을 구현중이라
아직 개발이 안끝나서 그렇습니다

[634b3cc786775f53fa27cdb8274a3c8c87678776](https://github.com/dltkddnr04/AfreecaTV-Auto-Recorder/tree/634b3cc786775f53fa27cdb8274a3c8c87678776)
사용하시면 닉네임만 넣을수 있지만 작동합니다

**Comment by Honinbo-Shusaku** [comment]
감사합니다😃
